Vagrant.configure("2") do |config|

IPSER = "192.168.56.201"
IPHOST = "192.168.56.203"
SERVER = "pdv-zabserv"
HOST = "pdv-zabclnt"


ZABBIX_NODES = { 'pdv-zabserv' => '192.168.56.201',
                  'pdv-zabclnt' => '192.168.56.203'}

ZABBIX_NODES.each do |node_name, node_ip|
config.vm.provision :shell do |s|
	  s.path = "./fin_script.sh"
      s.args = "#{IPSER} #{SERVER} #{IPHOST} #{HOST}"
    end
  end

ZABBIX_NODES.each do |node_name, node_ip|
    config.vm.define node_name do |node_config|
      node_config.vm.box = 'sbeliakou/centos'
      node_config.vm.box_url = 'sbeliakou/centos'
      node_config.vm.hostname = node_name
      node_config.vm.network :private_network, :ip => node_ip
	  node_config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
	  end
    end
  end
end

